### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Cubio** [lahell/PSDiscoveryProtocol#3]
ps admin
win10

![image](https://user-images.githubusercontent.com/1745275/64330988-ad5ec480-cfda-11e9-83cd-c31c31fa5219.png)

**Comment by lahell** [comment]
Would you mind sending me the output from the following code using the [contact form](https://www.powershellgallery.com/packages/PSDiscoveryProtocol/1.0.0/ContactOwners) on PowerShell Gallery?
    
    $Packet = Capture-LLDPPacket
    [System.Convert]::ToBase64String($Packet)

**Comment by lahell** [comment]
@Cubio: I would need the packet you captured to be sure, but I think I know what is going on.

Does it work if you remove the following code from `Parse-LLDPPacket`?
    
                1 {
                    # Chassis ID
                    $Subtype = $Packet[$Offset]
                    $Offset += 1
                    $Length -= 1
 
                    if ($Subtype -eq 4)
                    {
                        $ChassisID = [PSCustomObject] @{
                            Type = 'MAC Address'
                            ID = [PhysicalAddress]::new($Packet[$Offset..($Offset + 5)])
                        }
                        $Offset += 6
                    }

                    if ($Subtype -eq 6)
                    {
                        $ChassisID = [PSCustomObject] @{
                            Type = 'Interface Name'
                            ID = [System.Text.Encoding]::ASCII.GetString($Packet[$Offset..($Offset + $Length)])
                        }
                        $Offset += $Length
                    }
                    break
                }

**Comment by Cubio** [comment]
ok, I will to thous at the next Monday (output and removing some code).

**Comment by lahell** [comment]
Did it work when you removed the ChassisID section from `Parse-LLDPPacket`?

**Comment by lahell** [comment]
@Cubio: Have you had a chance to test?

**Comment by lahell** [comment]
I'm going to close this issue now because I don't have enough information.

I do think, however, that commit 1842bc9c8053f4a17847888df1d7790ce6bfb86e or commit 5e4ead7fc8d0b79add736367aa9e1c15f17ca2a5 could fix your issue. You can update to version 1.0.1 by running `Update-Module -Name PSDiscoveryProtocol`.

Please note that some devices only include the mandatory TLVs in their LLDP packets. The mandatory TLVs are ChassisID, PortID and Time To Live. This module will only return PortID and some of the optional TLVs. 

Try to do a packet capture with Wireshark and have a look at what information is available in your LLDP packets. If you think I should include some of that information, please let me know.
