### ISSUE TITLE
Any way to run without requiring Admin privilege's? 

### ISSUE THREAD

**Issue by s0nders** [lahell/PSDiscoveryProtocol#6]
Greetings,

Thank you for the work you've put into this, which portions of the module require admin privilege's and do you know of any work arounds?

Thanks!

**Comment by lahell** [comment]
Administrator privileges are required because of `Add-NetEventNetworkAdapter -Name $Adapter.Name -PromiscuousMode $True`. More specifically, the `PromiscuousMode` switch. 

CDP packets will have 01-00-0c-cc-cc-cc as destination address. LLDP packets will have one of 01-80-c2-00-00-0e, 01-80-c2-00-00-03, 01-80-c2-00-00-00 as destination address. Any packet where the destination address does not match the MAC address of the network adapter is dropped, unless the adapter is in promiscuous mode. Enabling promiscuous mode requires administrator privileges. I do not know of any workarounds.

**Comment by s0nders** [comment]
> Enabling promiscuous mode

Man I would love to use your work for some documentation scripts, that's a bummer :/ Thank you for responding, appreciate it.

**Comment by lahell** [comment]
Thank you for your kind words. I will close this issue as I'm unaware of any workaround.
