### ISSUE TITLE
Incomplete data displayed

### ISSUE THREAD

**Issue by ThatWhiteMonster** [lahell/PSDiscoveryProtocol#8]
Hi,

I've noticed that the IP Address property is not being displayed, if the CDP neighbor is an IP phone.
In "CaptureCDP" module, it was showing up. Screenshot below.
Is there a way to get that back?

![image](https://user-images.githubusercontent.com/19676500/90604113-a71e2400-e1fc-11ea-8117-2266d95f9d86.png)

If the CDP neighbor is a switch, the IP address is showing up fine.

**Comment by lahell** [comment]
Please try to reverse commit 74d86702d35c1072229e4bbb5d4ae076b0d94e16 to see if that fixes your issue.

**Comment by ThatWhiteMonster** [comment]
> Please try to reverse commit [74d8670](https://github.com/lahell/PSDiscoveryProtocol/commit/74d86702d35c1072229e4bbb5d4ae076b0d94e16) to see if that fixes your issue.

Yes, that did the trick 🙂 . Thank you 🙂 .

**Comment by lahell** [comment]
Fixed by commit 5b239f0d0ad2e5d3ece871c8118b93e5eba3de2c. The property `.IPAddress` will now be an array of IPv4 and IPv6 addresses from the Addresses TLV (0x0002). There is also a new property called `.Management` which will be an array of IPv4 and IPv6 addresses from the Management Addresses TLV (0x0016).
